Fixed reference to web-view
Provided commit hash wasn't present in repo:

```
error: failed to load source for a dependency on `web-view`

Caused by:
  Unable to update https://github.com/Freaky/web-view.git?rev=87a108fba963e701dc71a16d2f60ac54d96a09b5#87a108fb

Caused by:
  revspec '87a108fba963e701dc71a16d2f60ac54d96a09b5' not found; class=Reference (4); code=NotFound (-3)
```

I've tried fix-calling-convention  branch first, but in it FileOpenDialog wasn't working.
So I've chose  alternate-upstream and it works like a charm.